### ISSUE TITLE
Errors on admin creation : The key provided could not be used.

### ISSUE THREAD

**Issue by Nirvilus** [passbolt/passbolt_api#117]
Hello !

I'm struggling with an issue and can't get my hands out of it.
I've installed Passbolt on my Ubuntu 16.04 server with php7 running behind an nginx.

Installation succeeds without any flaw, but problems are starting as I create my admin account.

On process ending, my browser prints the following error :

> Error! Something unexpected happened. The setup cannot be completed.
```
{
  "error": "server response error",
  "setup": {
    "stepId": "login_redirection",
    "stepsHistory": "domain_check/define_key/key_info/security_token",
    "user": {
      "username": "me@mydomain.me",
      "firstname": "me",
      "lastname": "mydomain,
      "id": "59625a5f-8700-4b37-bd53-03c236297fdb"
    },
    "key": {
      "privateKeyArmored": "",
      "publicKeyArmored": "-----BEGIN PGP PUBLIC KEY BLOCK-----\r\nVersion: OpenPGP.js v2.3.7\r\nComment: http://openpgpjs.org\r\n\r\nxsBNBFliVBQBCACaen3zo3VvocpZhrzjoLTgR2cEaTz0VVfkZP+daRBVGDGW\nroiIff4i9SunNYAIcZlb3ZrrsFRLgHTulZ6hv4+nIxtf5ataNeBydlnLXX/4\nMyZ+yDWEiQ627Xd2myjTSo4qDXkYU5PLRCLwcjWRQy0iax9suzsZ4huQ+l6P\nf6WVa1zCDJI2enk5Zz9vURybQda6H9ZmoPJrA80gD5enQpPyPo7yL6qWCrHX\nbXY4gytseWnI+lvXUcUpKbdOfyPZcVCvwSh/SP8orp7wdVYgxnUPtFHMKYPA\nuLhb92xs78JkOMox+H0duON4m62FXBcMI5q7X3EaZigG0jrXq67GHE8jABEB\nAAHNIk5pY29sYXMgRXlyYXVkIDxuaWNvbGFzQGV5cmF1ZC5tZT7CwHUEEAEI\nACkFAlliVBgGCwkHCAMCCRB2kvlTi3Q5UgQVCAIKAxYCAQIZAQIbAwIeAQAA\nPmcH/i8wVniZQcgNNYEikukV/IGvkHqyPbhb/kLBaHWujW+ub38cowJLsDv8\nsgOzA54cv2IlzoHOyb/T8rmhQP3FOm4uuwZ42e69igPL6oNgObGbxHOsCeC/\nssz7tETBBBMsz+jRPBOATNpDC3J5CCNXpdlWQzK0MOrE0Gxl0CweXrZ/SCw3\nmHUbIPGKzG6dIEynRepE+08RYmzuOvL3men/xEC9GxgKpgU1hdSpbhbcpLsd\nEz8jtHTsMqupoAwzqcdzvVW5Mkr024FLEpVf23gEiGZRf78l82PcbvcT7ooI\nUlkTXiYLC14UqicgC/qsENY6Ot/YwU/1d1Q4XZD7rAdbpi7OwE0EWWJUFQEI\nAKgVrHriLY70ejkhQngDh3zPwWE30ZmoFm/jZz4QOVROXTuoQQQ35B8qDFXs\nDzsicNjX8K9s/Lz1Lym0gyFHWxAL1///xDed+TUStb151KkJrVqvwG7Va7/e\npMEYLpV2fuU8TSKEsU2M2Jmk0bZRQdK1HFS6bQGBaObkagtsmG+gN9n1tc+H\nslMQmX9HnU44C2Psgin8CVzAWds+x9Ag4j/NybMwwtBdA5xNd3BMUHLrXP6M\nPCdiQCVl0jRBbwgUJIKCpih5VpDLNGuZJ1JkBMb/K/exAaYjEV4riMRcXiCS\nk7GBafxlbMcsFLFM128VaPwzJq2F6x88NtzA+8g2nasAEQEAAcLAXwQYAQgA\nEwUCWWJUGAkQdpL5U4t0OVICGwwAALuSB/0Xr6tovmZmsGh1sCWWZXiW7hR5\ngw1oFsmn2cQ+Ellql10i88hoQv3NPMfkqRtoVcERqIpuHyjH6QAuIdJUR1xx\ndpRkxewMBjluXtqjo3+MMrgg4vgljBESMf1qC6pvJr/PcyBhP/q/nX9m5Gvz\ntu3ZlWZ9ToTi9spLsF7Ipw1h10sfUN7FmpzO+tyf7Z0zjHUu9NbCB0EXTPG8\nplUoVfoKK27yI4OqCMHFwpyx+ksRRr9hO8fPdb6CNdOQ3+9clowLXCPtjpRH\nc9Qj/RlEJiXm7iGaN7Xwc+COq9arnSadilGMt6PPSlDE2AxC4dpmygHZ2l0K\nG+Qh4Anqdx9CNmV1\r\n=YJrV\r\n-----END PGP PUBLIC KEY BLOCK-----\r\n\r\n"
    },
    "settings": {
      "token": "485b55f8-6aed-4289-a674-96869de2a2c6",
      "domain": "https://passbolt.mydomain.me",
      "armoredServerKey": "-----BEGIN PGP PUBLIC KEY BLOCK-----\nVersion: GnuPG v1\n\nmQENBFliU0ABCADcavVHtdejcAI42p27Ez78skkW5w/A7tVRIKJ6pPJKxHt8PtYP\nl7gDOm8ELGRMODCA3oRgRaYvhUIC1P4nBPZ5FnQEtRkadasKUdGN+jNGc1S2NtVy\n2QI6Cy4dmlo1KACC/OaneG2RCBjqGmnBDNH/qZ11qUK80QViF5HD/DxzGDo4BDfD\nJOuSjkH1eGFBOVcbVcEj9LkLOPzZtbFnbtBs5u1GaXWIjs1s45nXSJ704oAZO7Kn\niy1clQPmcEbI0EBJ41GaGsqfiXxbWSvHqghqMGS5nhOQg7z3+UpPUQBMdg8lRevK\nF4B81l6hmTvZzjTf5++L6X6QsuJW3M8Pq3OzABEBAAG0KE1hc3RlcktleSA8cGFz\nc2JvbHQubWFzdGVya2V5QGV5cmF1ZC5tZT6JATgEEwECACIFAlliU0ACGwMGCwkI\nBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJED1iN6mCN5bZwX8IAMyP6vHomJlygMsT\nqgValjbUf/CetWXNwidWMUk/qoxIXa7mi5NAVL0z/YuVK5GZdVCHMFIQUhAaZ1rM\nnS5p4pTzWz7rpsHasJm0boTFyeadlSUC3klTflVKAAkBRJ8bCoZ9AC590UTL7Unf\nA45GJcaoJfxl8dqDwd993EszQIOCWkhschIowtNOYC8HibN/dpPQTM1alHmI4+an\nKXx7YWNBAsw7UB2vU9AcmL5KLfHfwG7VFDz1EC4aoD3r01yWxBiW65uEM95dD18x\nRIKoI/st+jE1W5MKpTmA/EGw3jfwYXOd8zSyl1s5T0OOXejBa03BP418GqadIrY9\nUl7tFDC5AQ0EWWJTQAEIAPHAmPSin2414vsjogXMzx01vnOjiwDY/ZlJBwneCj+R\nRjINNdkVcYxrAbSMZ5SCWFhLIcLa2Qu/sBrYm3h9p2GS3+hELLZrwqzt7etrYSys\nHgkExm+oVmRgVCNGWJgl+okL+iELc+anvoTA7LxReJUjKChHv9BXjZj4goJu+nEW\n0WQcZoubI4wtc+yRTYLAIXi7maLHlvk+EzcsAgWfFqTGc5Bzckg8cRSox+hNLID+\nzyh6McuJln71KkFyTbTK4MZdgeROwNa4R0H2jSrChCmwdZxAbk8PXUiQSWzR8tkA\nWHibm4f4V6etHS7Siy7o546OIAhkrCdFl5MyLj3SSRkAEQEAAYkBHwQYAQIACQUC\nWWJTQAIbDAAKCRA9YjepgjeW2cqJB/9c4lmBWK6ZcY96PmbsAIqATRravjcdyxjD\nxFIvQcqfYxFpU/8REnlFYtQgLMEuwfcCrqp085eT7I20Qb0nBG2kFJF/6VbAaVjZ\nyGPs+EnhliDdvjKVp8Bpycj1FoI10MSzRJc/BcsCj2L40fNSUrasch8YIfWdfEjj\ncaWOLGezxfOCKdkOmo9vwft1s2dVDrugrDbwKB4T1da3UhvzrTrSiz1hquRS3Epd\nZwP0M3WcSe8Hi6VmJnWg2lGtEO2LpJYw4UOPbBuC5jVllmYJsMiVxrZ6ckyrJJzG\no0GShO6XNvidjjAYK/4TtLPCybOZo97yx1gRvdXg+Yeyx+DNx1S0\n=GURY\n-----END PGP PUBLIC KEY BLOCK-----\n",
      "securityToken": {
        "code": "kv-",
        "color": "#345D7C",
        "textcolor": "#fff"
      }
    }
  },
  "additional": {
    "request": {
      "AuthenticationToken": {
        "token": "485b55f8-6aed-4289-a674-96869de2a2c6"
      },
      "Gpgkey": {
        "key": "-----BEGIN PGP PUBLIC KEY BLOCK-----\r\nVersion: OpenPGP.js v2.3.7\r\nComment: http://openpgpjs.org\r\n\r\nxsBNBFliVBQBCACaen3zo3VvocpZhrzjoLTgR2cEaTz0VVfkZP+daRBVGDGW\nroiIff4i9SunNYAIcZlb3ZrrsFRLgHTulZ6hv4+nIxtf5ataNeBydlnLXX/4\nMyZ+yDWEiQ627Xd2myjTSo4qDXkYU5PLRCLwcjWRQy0iax9suzsZ4huQ+l6P\nf6WVa1zCDJI2enk5Zz9vURybQda6H9ZmoPJrA80gD5enQpPyPo7yL6qWCrHX\nbXY4gytseWnI+lvXUcUpKbdOfyPZcVCvwSh/SP8orp7wdVYgxnUPtFHMKYPA\nuLhb92xs78JkOMox+H0duON4m62FXBcMI5q7X3EaZigG0jrXq67GHE8jABEB\nAAHNIk5pY29sYXMgRXlyYXVkIDxuaWNvbGFzQGV5cmF1ZC5tZT7CwHUEEAEI\nACkFAlliVBgGCwkHCAMCCRB2kvlTi3Q5UgQVCAIKAxYCAQIZAQIbAwIeAQAA\nPmcH/i8wVniZQcgNNYEikukV/IGvkHqyPbhb/kLBaHWujW+ub38cowJLsDv8\nsgOzA54cv2IlzoHOyb/T8rmhQP3FOm4uuwZ42e69igPL6oNgObGbxHOsCeC/\nssz7tETBBBMsz+jRPBOATNpDC3J5CCNXpdlWQzK0MOrE0Gxl0CweXrZ/SCw3\nmHUbIPGKzG6dIEynRepE+08RYmzuOvL3men/xEC9GxgKpgU1hdSpbhbcpLsd\nEz8jtHTsMqupoAwzqcdzvVW5Mkr024FLEpVf23gEiGZRf78l82PcbvcT7ooI\nUlkTXiYLC14UqicgC/qsENY6Ot/YwU/1d1Q4XZD7rAdbpi7OwE0EWWJUFQEI\nAKgVrHriLY70ejkhQngDh3zPwWE30ZmoFm/jZz4QOVROXTuoQQQ35B8qDFXs\nDzsicNjX8K9s/Lz1Lym0gyFHWxAL1///xDed+TUStb151KkJrVqvwG7Va7/e\npMEYLpV2fuU8TSKEsU2M2Jmk0bZRQdK1HFS6bQGBaObkagtsmG+gN9n1tc+H\nslMQmX9HnU44C2Psgin8CVzAWds+x9Ag4j/NybMwwtBdA5xNd3BMUHLrXP6M\nPCdiQCVl0jRBbwgUJIKCpih5VpDLNGuZJ1JkBMb/K/exAaYjEV4riMRcXiCS\nk7GBafxlbMcsFLFM128VaPwzJq2F6x88NtzA+8g2nasAEQEAAcLAXwQYAQgA\nEwUCWWJUGAkQdpL5U4t0OVICGwwAALuSB/0Xr6tovmZmsGh1sCWWZXiW7hR5\ngw1oFsmn2cQ+Ellql10i88hoQv3NPMfkqRtoVcERqIpuHyjH6QAuIdJUR1xx\ndpRkxewMBjluXtqjo3+MMrgg4vgljBESMf1qC6pvJr/PcyBhP/q/nX9m5Gvz\ntu3ZlWZ9ToTi9spLsF7Ipw1h10sfUN7FmpzO+tyf7Z0zjHUu9NbCB0EXTPG8\nplUoVfoKK27yI4OqCMHFwpyx+ksRRr9hO8fPdb6CNdOQ3+9clowLXCPtjpRH\nc9Qj/RlEJiXm7iGaN7Xwc+COq9arnSadilGMt6PPSlDE2AxC4dpmygHZ2l0K\nG+Qh4Anqdx9CNmV1\r\n=YJrV\r\n-----END PGP PUBLIC KEY BLOCK-----\r\n\r\n"
      }
    },
    "response": {
      "header": {
        "id": "9bf47528-77ef-3d3f-aefc-2c398e536538",
        "status": "error",
        "title": "app_users_validateaccount_error",
        "servertime": 1499617938,
        "controller": "users",
        "action": "validateAccount",
        "message": "The key provided could not be used."
      }
    }
  }
}
```

The corresponding cakephp log is:
```
2017-07-09 18:32:18 Error: [BadRequestException] The key provided could not be used.
Request URL: /users/validateAccount/59625a5f-8700-4b37-bd53-03c236297fdb.json
Stack Trace:
#0 [internal function]: UsersController->validateAccount('59625a5f-8700-4...')
#1 /var/www/passbolt/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#2 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#4 /var/www/passbolt/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```

As a debugging approach, I wondered wether it could be my gpg key import function bugging.
I tried to re-register using private key import.

My browsers tells me key could be sucessfully parsed:

> Success! Nice one, it looks like a valid key with your key information matching the name and email provided by your passbolt administrator. 
> 
> You are good to go!

... while my cakephp logs tells me otherwise:
```
2017-07-09 18:52:16 Error: [Error] Class 'gnupg' not found
Request URL: /auth/verify.json
Stack Trace:
#0 /var/www/passbolt/app/Controller/Component/Auth/GpgAuthenticate.php(49): GpgAuthenticate->_initKeyring()
#1 /var/www/passbolt/lib/Cake/Controller/Component/AuthComponent.php(770): GpgAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#2 /var/www/passbolt/lib/Cake/Controller/Component/AuthComponent.php(611): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#3 /var/www/passbolt/app/Controller/AuthController.php(72): AuthComponent->login()
#4 [internal function]: AuthController->verify()
#5 /var/www/passbolt/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(AuthController), Array)
#6 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AuthController), Object(CakeRequest))
#8 /var/www/passbolt/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
```
The registration process ended up with the very same error.

The strange thing about this seccond error is that nor the setup script nor my manual checks reports an error with my gnupg class:
```
root@mydomain:/var/www/passbolt# php -i | grep gnupg
/etc/php/7.0/cli/conf.d/20-gnupg.ini,
gnupg
gnupg support => enabled
```

I'm kind of lost, and can't find informations helping me.

Does anyone have an insight ?
Thank you

**Comment by ktosiek** [comment]
There are 2 separate bindings to GnuPGP in PHP. I think passbolt uses the `php-gnupg` one - are you sure that's the one you've got?

**Comment by ktosiek** [comment]
Also, do you have multiple versions of PHP on that server? Maybe you are using one for CLI and other for WWW

**Comment by stripthis** [comment]
Hi @Nirvilus,

Could you check as @ktosiek mentionned that you have gnupg.so included in the php.ini used by your webserver (like you have for the cli).

Cheers,

**Comment by stripthis** [comment]
Closing due to inactivity. Please feel free to reopen if you are still experiencing the issue.
