### ISSUE TITLE
Oops, something went wrong

### ISSUE THREAD

**Issue by rfacio** [passbolt/passbolt_api#127]
Hello,

I'm having a problem to setup the Passbolt on Debian 8 with the reference guide ["Passbolt on Debian 8 “jessie” from scratch",](https://medium.com/passbolt/passbolt-on-debian-8-71-from-scratch-4438dad18908) after that I created the user I couldn't login.

![image](https://user-images.githubusercontent.com/30437273/28573583-769fd674-7121-11e7-93fd-7a935da9ec16.png)

Any idea?

**Comment by stripthis** [comment]
Can you see any error message in the browser console? 

You can open the Browser Console in one of two ways:
- from the menu: select "Browser Console" from the Web Developer submenu in the Firefox Menu (or Tools menu if you display the menu bar or are on OS X)
- from the keyboard: press Ctrl+Shift+J (or Cmd+Shift+J on a Mac).

**Comment by rfacio** [comment]
No I just have a error on the security tab because the certificate is not trusted.

![image](https://user-images.githubusercontent.com/30437273/28575515-7e24a14e-7127-11e7-9f94-5982bba639c4.png)

**Comment by rfacio** [comment]
I already saw the healthcheck and I don't receive any errors:

root@passbolt:/var/www/passbolt# ./app/Console/cake passbolt healthcheck
---------------------------------------------------------------
     ____                  __          ____
    / __ \____  _____ ____/ /_  ____  / / /_
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /
 /_/    \__,_/____/____/_.___/\____/_/\__/

 Open source password manager for teams
---------------------------------------------------------------
 Healthcheck shell
---------------------------------------------------------------

 Environment

 [PASS] PHP version 5.6.30-0+deb8u1
 [PASS] PCRE compiled with unicode support
 [PASS] The app/tmp directory is writable
 [PASS] The app/webroot/img/public directory is writable

 Config files

 [PASS] The core config file is present
 [PASS] The database config file is present
 [PASS] The email config file is present
 [PASS] The application config file is present

 Core config

 [PASS] Debug mode is off.
 [PASS] Cache is working.
 [PASS] Unique value set for security.salt
 [PASS] Unique value set for security.cipherSeed
 [PASS] Full base url is set to https://passbolt.dev
 [PASS] App.fullBaseUrl validation OK.
 [PASS] /healthcheck/status is reachable.

 SSL Certificate

 [PASS] SSL peer certificate validates
 [PASS] Hostname is matching in SSL certificate.
 [WARN] Using a self-signed certificate

 Database

 [PASS] Configured to use a supported database backend
 [PASS] The application is able to connect to the database
 [PASS] Not using a prefix for database tables
 [PASS] 20 tables found
 [PASS] Some default content is present
 [PASS] The database schema up to date.

 GPG Configuration

 [PASS] PHP GPG Module is installed and loaded
 [PASS] The server gpg key is not the default one
 [PASS] The environment variable GNUPGHOME is set to /home/www-data/.gnupg
 [PASS] The directory containing the keyring is writable by root.

 Application configuration

 [PASS] Using latest passbolt version (1.6.0)
 [PASS] Passbolt is configured to force SSL use
 [PASS] App.fullBaseUrl is set to HTTPS
 [PASS] Selenium API endpoints are disabled.
 [PASS] Search engine robots are told not to index content.
 [PASS] Registration is closed, only administrators can add users.
 [PASS] Serving the compiled version of the javascript app

 Development Tools (optional)

 [PASS] Phpunit is installed
 [PASS] Phpunit version is 3.7.38

 No error found. Nice one sparky!

I think that can be anything on apache rewrite... my file are:

**/etc/apache2/sites-enabled/default-ssl.conf**
<ifModule mod_ssl.c>
    <VirtualHost _default_:443>
        ServerAdmin webmaster@localhost
        ServerName passbolt.dev
        DocumentRoot /var/www/passbolt
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        SSLEngine on
        SSLCertificateFile /etc/apache2/ssl/apache.crt
        SSLCertificateKeyFile /etc/apache2/ssl/apache.key

        <Directory /var/www/passbolt>
            Options FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>

        <FilesMatch “\.(php)$”>
            SSLOptions +StdEnvVars
        </FilesMatch>
        BrowserMatch “MSIE [2–6]” \
          nokeepalive ssl-unclean-shutdown \
          downgrade-1.0 force-response-1.0
        BrowserMatch “MSIE [17–9]” ssl-unclean-shutdown
    </VirtualHost>
</IfModule>
# vim: syntax=apache ts=4 sw=4 sts=4 sr noet


**/var/www/passbolt/.htaccess**
<IfModule mod_rewrite.c>
        RewriteEngine on
        # Uncomment if you have a .well-known directory in the root folder, e.g. for the Let's Encrypt challenge
        # https://tools.ietf.org/html/rfc5785
        #RewriteRule ^(\.well-known/.*)$ $1 [L]
        RewriteRule ^$ app/webroot/ [L]
        RewriteRule (.*) app/webroot/$1 [L]
</IfModule>
# Keep a newline at end of file

**Comment by stripthis** [comment]
Can you inspect the plugin views in chrome://extension to see if there is an error there? Something like this:

<img width="1274" alt="screen shot 2017-07-27 at 13 23 56" src="https://user-images.githubusercontent.com/77410/28659998-f65fcf0a-72ce-11e7-80ed-f876cf8c891d.png">

**Comment by mannp** [comment]
I have the same error from a previously working extension.

Not sure I am looking in the right place, but these errors seem to be for passbolt;

Error in event handler for (unknown): TypeError: Cannot read property 'emit' of undefined
    at Port.eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/event/configEvents.js:103:16)
    at eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/sdk/port.js:26:16)
index.html:1 Error in event handler for (unknown): TypeError: Cannot read property 'emit' of undefined
    at Port.eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/event/keyringEvents.js:93:18)
    at eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/sdk/port.js:26:16)
index.html:1 Error in event handler for (unknown): TypeError: Cannot read property 'emit' of undefined
    at Port.eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/event/configEvents.js:50:16)
    at eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/sdk/port.js:26:16)
index.html:1 Error in event handler for (unknown): TypeError: Cannot read property 'url' of undefined
    at Port.eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/event/configEvents.js:66:30)
    at eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/sdk/port.js:26:16)
index.html:1 Error in event handler for (unknown): TypeError: Cannot read property 'emit' of undefined
    at Port.eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/event/configEvents.js:78:16)
    at eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/sdk/port.js:26:16)
index.html:1 Error in event handler for (unknown): TypeError: Cannot read property 'emit' of undefined
    at Port.eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/event/configEvents.js:103:16)
    at eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/sdk/port.js:26:16)
index.html:1 Error in event handler for (unknown): TypeError: Cannot read property 'emit' of undefined
    at Port.eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/event/keyringEvents.js:93:18)
    at eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/sdk/port.js:26:16)
index.html:1 Error in event handler for (unknown): TypeError: Cannot read property 'emit' of undefined
    at Port.eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/event/configEvents.js:50:16)
    at eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/sdk/port.js:26:16)
index.html:1 Error in event handler for (unknown): TypeError: Cannot read property 'url' of undefined
    at Port.eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/event/configEvents.js:66:30)
    at eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/sdk/port.js:26:16)
index.html:1 Error in event handler for (unknown): TypeError: Cannot read property 'emit' of undefined
    at Port.eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/event/configEvents.js:78:16)
    at eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/sdk/port.js:26:16)
index.html:1 Error in event handler for (unknown): TypeError: Cannot read property 'emit' of undefined
    at Port.eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/event/configEvents.js:103:16)
    at eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/sdk/port.js:26:16)
index.html:1 Error in event handler for (unknown): TypeError: Cannot read property 'emit' of undefined
    at Port.eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/event/keyringEvents.js:93:18)
    at eval (chrome-extension://didegimhafipceonhjepacocaffmoppf/lib/sdk/port.js:26:16)

**Comment by stripthis** [comment]
Hi @mannp, any chance you could tell us what happened between having the working extension and getting it to this state? Like your browser got udpated, you added/removed the extension, etc. Any hint that could help us reproduce the issue would be much appreciated.

**Comment by mannp** [comment]
Hi @stripthis I am trying to get email working on my mac using your docker and so I have been rebooting the docker testing out many email configs.

Chrome has not been updated and has just been left logged into my admin account, with the password list in view.

After rebooting the docker a few times I went back to the open account window on chrome and refreshed.

It immediately gave me that oops window and I am unable to log back in.

Also, without email configured I am unable to swap to firefox as it seems it needs the account recovered to store the corrects keys I presume.

**Comment by mannp** [comment]
@stripthis I kept refreshing the login page and it seems to be trying to check another gpg key and it highlighted that key like a url, which I clicked and it showed me the following;

Missing Method in AuthController

Error: The action auth is not defined in controller AuthController

Error: Create AuthController::auth() in file: app/Controller/AuthController.php.

<?php
class AuthController extends AppController {


	public function auth() {

	}

}
Notice: If you want to customize this error message, create app/View/Errors/missing_action.ctp

Stack Trace

CORE/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
CORE/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(AuthController, CakeRequest)
APP/webroot/index.php line 111 → Dispatcher->dispatch(CakeRequest, CakeResponse)
ROOT/index.php line 41 → require(string)

**Comment by mannp** [comment]
For me it seems that the gpg: key is changed between reboots of the server and the plugin, both chrome and firefox lose track of the config.

I am not able to rectify except to remove the plugin and recover the account.

I am hoping now I have things as I want them the chances of the server key getting changed is massively reduced so this problem should go away.

That said its annoying and there is no explanation of what is happening from the plugin.

**Comment by stripthis** [comment]
Closing due to inactivity and lack of information. Please reopen a new issue if needed.

**Comment by MackieeE** [comment]
This question/ticket ranked high on Google. For me, it was because the self-signed cert URL did not match the login page URL.
