### ISSUE TITLE
The server was unable to respect the authentication protocol! (Centos7 / PHP7)

### ISSUE THREAD

**Issue by eraxor** [passbolt/passbolt_api#141]
Hi got following problem with new Setup on nginx/1.13.4, PHP 7.0.21 

> The server was unable to respect the authentication protocol! There was a problem when trying to communicate with the server (HTTP Code:500)

![passbolt](https://user-images.githubusercontent.com/30867676/29123545-660c465c-7d16-11e7-83e2-6cc687b83025.PNG)

```
2017-08-09 13:18:02 Error: [Exception] encrypt-sign failed
Request URL: /auth/login.json
Stack Trace:
#0 /var/www/html/passbolt/app/Controller/Component/Auth/GpgAuthenticate.php(109): gnupg->encryptsign('gpgauthv1.3.0|3...')
#1 /var/www/html/passbolt/lib/Cake/Controller/Component/AuthComponent.php(770): GpgAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#2 /var/www/html/passbolt/lib/Cake/Controller/Component/AuthComponent.php(611): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#3 /var/www/html/passbolt/app/Controller/AuthController.php(35): AuthComponent->login()
#4 [internal function]: AuthController->login()
#5 /var/www/html/passbolt/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(AuthController), Array)
#6 /var/www/html/passbolt/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/html/passbolt/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AuthController), Object(CakeRequest))
#8 /var/www/html/passbolt/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
```
regards

Sascha

![passbolt_headers](https://user-images.githubusercontent.com/30867676/29123538-61f86172-7d16-11e7-9d78-bcebe2c36dc4.PNG)

**Comment by stripthis** [comment]
HI @eraxor it looks like the server is enable to encrypt with that user key. Did you generate this key from passbolt or did you import it? Can you try with another user / key?

**Comment by eraxor** [comment]
Hi @stripthis ,
same behavior with new created Account.

**Comment by stripthis** [comment]
Which browser are you using? Do you get the same when using firefox or chrome?

**Comment by eraxor** [comment]
Ive tested with Chrome and Firefox. Both up2date.

**Comment by eraxor** [comment]
Grmpf, everything works fine on a new installed Debian Jessie and php5.
Anyway, would be nice if we get it running on Centos 7 with php7.

**Comment by stripthis** [comment]
@eraxor I will try a fresh install with your config see if I can reproduce the issue. Thanks for the follow up.

**Comment by eraxor** [comment]
@stripthis I've reinstalled on Centos 7 again, but this time i've used rng-tools from scratch and now i was able to login successfully . Same Install Steps. Maybe there is a problem with gnupg without rng-tools? Dunno...

thanks and regards

**Comment by stripthis** [comment]
Just to clarify @eraxor you are using it on a virtual machine right? Which VM system (software version and host OS) are you using? I'll keep this issue open so that we can investigate further.

**Comment by eraxor** [comment]
Yes, Virtual Maschine.

VMware ESXi, 6.5.0, 5310538

**Comment by stripthis** [comment]
ref. PASSBOLT-2345

**Comment by hurr1k4ne** [comment]
Hey, same problem here.
Set up a test install on:
-VirtualBox 5.1.22 r115126 (Qt5.6.2)
-Ubuntu LTS 16.04.3 (upgraded per 21.08.2017)
-passbolt 1.6.2
-Chrome Version 60.0.3112.101 (Offizieller Build) (64-Bit)

server was unable to respect authentification protocol (with F12 network console open)
just redirects to password login page without F12 console.

No errors logged, debug enabled.

**Comment by kevinmuller** [comment]
Hi @hurr1k4ne and @eraxor 

If you generated a test key for the server and you still have it, could you provide it so that I can run some tests locally? I suspect that it's an entropy problem at the key level.

You can send it to me by email at contact [@t] passbolt.com

Let me know. I am anyway trying to reproduce it in the meantime.

**Comment by eraxor** [comment]
Hi @kevinmuller,

I've deleted the non functional VM.

Sorry

**Comment by kevinmuller** [comment]
We currently ruled out that it can be due to GPG2, or a lack of entropy on the server. Can't reproduce for now.

**Comment by stripthis** [comment]
Closing due to inactivity.
