### ISSUE TITLE
Can't pass login page (Firefox)

### ISSUE THREAD

**Issue by tmidi** [passbolt/passbolt_api#143]
After setting up admin account successfully, I am not able to login using this account. After entering my password, I get redirected to the login page again, checking passbolt logs shows:

```
2017-08-10 16:08:41 Error: [ForbiddenException] You need to login to access this location
Request URL: /auth/checkSession.json
Stack Trace:
#0 /var/www/html/passbolt/lib/Cake/Controller/Component/AuthComponent.php(349): GpgAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/html/passbolt/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(AuthController))
#2 /var/www/html/passbolt/lib/Cake/Utility/ObjectCollection.php(128): AuthComponent->startup(Object(AuthController))
#3 /var/www/html/passbolt/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('startup')
#4 /var/www/html/passbolt/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#5 /var/www/html/passbolt/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#6 /var/www/html/passbolt/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AuthController), Object(CakeRequest))
#7 /var/www/html/passbolt/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 {main}
```

Permission wise, I have set 
```
chown nginx:nginx app/Config
chmod -R 777 app/tmp
chmod -R 777 app/webroot/img/public`
```
Health check shows no error:
``` Environment

 [PASS] PHP version 7.0.21
 [PASS] PCRE compiled with unicode support
 [PASS] The app/tmp directory is writable
 [PASS] The app/webroot/img/public directory is writable

 Config files

 [PASS] The core config file is present
 [PASS] The database config file is present
 [PASS] The email config file is present
 [PASS] The application config file is present

 Core config

 [FAIL] Debug mode is on.
  [HELP] Set Configure::write('debug', 0); in app/Config/core.php
 [PASS] Cache is working.
 [PASS] Unique value set for security.salt
 [PASS] Unique value set for security.cipherSeed
 [PASS] Full base url is set to https://passbolt.localdomain.com
 [PASS] App.fullBaseUrl validation OK.
 [PASS] /healthcheck/status is reachable.

 SSL Certificate

 [PASS] SSL peer certificate validates
 [PASS] Hostname is matching in SSL certificate.
 [WARN] Using a self-signed certificate

 Database

 [PASS] Configured to use a supported database backend
 [PASS] The application is able to connect to the database
 [PASS] Not using a prefix for database tables
 [PASS] 20 tables found
 [PASS] Some default content is present
 [PASS] The database schema up to date.

 GPG Configuration

 [PASS] PHP GPG Module is installed and loaded
 [PASS] The server gpg key is not the default one
 [PASS] The environment variable GNUPGHOME is set to /opt/passbolt/.gnupg
 [PASS] The directory containing the keyring is writable by root.

 Application configuration

 [PASS] Using latest passbolt version (1.6.1)
 [PASS] Passbolt is configured to force SSL use
 [PASS] App.fullBaseUrl is set to HTTPS
 [PASS] Selenium API endpoints are disabled.
 [PASS] Search engine robots are told not to index content.
 [PASS] Registration is closed, only administrators can add users.
 [PASS] Serving the compiled version of the javascript app

 Development Tools (optional)

 [PASS] Phpunit is installed
 [PASS] Phpunit version is 3.7.38

  1 error(s) found. Hang in there!
```
I also have SELinux set to Permissive.
Am I missing something? or there is any other logs to help debug this issue?
Thanksget

**Comment by stripthis** [comment]
Hello @tmidi, the checksession error is not an error per say, it's just a check from the client to see if there an active login, so you can ignore that (we have another ticket to hide this from the error log at some point ref. PASSBOLT-2139).

Concerning your issue, could you show us the browser console logs as well as the network trace?

**Comment by tmidi** [comment]
@stripthis,
Please let me know if the logs below help
```
14:53:57.686 GET https://passbolt.localdomain.com/ [HTTP/1.1 302 Found 35ms]
14:53:57.759 GET https://passbolt.localdomain.com/users/login [HTTP/1.1 301 Moved Permanently 0ms]
14:53:57.779 GET https://passbolt.localdomain.com/auth/login [HTTP/1.1 200 OK 68ms]
14:53:58.249 GET https://passbolt.localdomain.com/css/login.min.css [HTTP/1.1 200 OK 0ms]
14:53:58.254 GET https://passbolt.localdomain.com/css/devel.min.css [HTTP/1.1 200 OK 0ms]
14:53:58.271 GET https://passbolt.localdomain.com/js/lib/modernizr/modernizr-custom.min.js [HTTP/1.1 200 OK 0ms]
14:53:58.279 GET https://passbolt.localdomain.com/js/lib/jquery/dist/jquery.js [HTTP/1.1 200 OK 0ms]
14:53:58.290 GET https://passbolt.localdomain.com/js/lib/steal/steal.production.js [HTTP/1.1 200 OK 0ms]
14:53:58.263 Expected declaration but found ‘*’.  Skipped to next declaration.  login.min.css:10:58
14:53:58.263 Unknown property ‘zoom’.  Declaration dropped.  login.min.css:10:472
14:53:58.263 Unknown property ‘-moz-border-radius’.  Declaration dropped.  login.min.css:10:616
14:53:58.263 Expected declaration but found ‘*’.  Skipped to next declaration.  login.min.css:10:1974
14:53:58.263 Expected declaration but found ‘*’.  Skipped to next declaration.  login.min.css:10:1990
14:53:58.263 Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped.  login.min.css:10:2135
14:53:58.263 Expected declaration but found ‘*’.  Skipped to next declaration.  login.min.css:10:3379
14:53:58.263 Expected declaration but found ‘*’.  Skipped to next declaration.  login.min.css:10:3474
14:53:58.264 Expected declaration but found ‘*’.  Skipped to next declaration.  login.min.css:10:3672
14:53:58.264 Expected declaration but found ‘*’.  Skipped to next declaration.  login.min.css:10:3814
14:53:58.264 Expected declaration but found ‘*’.  Skipped to next declaration.  login.min.css:10:3827
14:53:58.264 Unknown pseudo-class or pseudo-element ‘-webkit-search-cancel-button’.  Ruleset ignored due to bad selector.  login.min.css:10:3859
14:53:58.264 Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped.  login.min.css:13:643
14:53:58.264 Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  login.min.css:13:1882
14:53:58.264 Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  login.min.css:13:2045
14:53:58.264 Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  login.min.css:13:2211
14:53:58.264 Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  login.min.css:13:2382
14:53:58.264 Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  login.min.css:13:2552
14:53:58.266 Unknown pseudo-class or pseudo-element ‘-webkit-input-placeholder’.  Ruleset ignored due to bad selector.  login.min.css:13:27431
14:53:58.266 Unknown property ‘-moz-box-shadow’.  Declaration dropped.  login.min.css:13:28258
14:53:58.266 Unknown property ‘-moz-box-shadow’.  Declaration dropped.  login.min.css:13:28532
14:53:58.266 Error in parsing value for ‘cursor’.  Declaration dropped.  login.min.css:13:28559
14:53:58.266 Unknown property ‘zoom’.  Declaration dropped.  login.min.css:13:30184
14:53:58.266 Expected declaration but found ‘*’.  Skipped to next declaration.  login.min.css:13:30187
14:53:58.266 Error in parsing value for ‘background-image’.  Declaration dropped.  login.min.css:13:30488
14:53:58.266 Expected color but found ‘background-lightest’.  Error in parsing value for ‘background-image’.  Declaration dropped.  login.min.css:13:30583
14:53:58.266 Error in parsing value for ‘background-image’.  Declaration dropped.  login.min.css:13:30690
14:53:58.266 Expected color but found ‘top’.  Error in parsing value for ‘background-image’.  Declaration dropped.  login.min.css:13:30760
14:53:58.266 Unknown property ‘-moz-border-radius’.  Declaration dropped.  login.min.css:13:30825
14:53:58.267 Error in parsing value for ‘background-image’.  Declaration dropped.  login.min.css:13:31794
14:53:58.267 Expected color but found ‘background-lightest’.  Error in parsing value for ‘background-image’.  Declaration dropped.  login.min.css:13:31889
14:53:58.267 Error in parsing value for ‘background-image’.  Declaration dropped.  login.min.css:13:31996
14:53:58.267 Expected color but found ‘top’.  Error in parsing value for ‘background-image’.  Declaration dropped.  login.min.css:13:32066
14:53:58.267 Unknown property ‘-moz-box-shadow’.  Declaration dropped.  login.min.css:13:32346
14:53:58.267 Unknown property ‘-moz-box-shadow’.  Declaration dropped.  login.min.css:13:32880
14:53:58.267 Unknown property ‘-moz-box-shadow’.  Declaration dropped.  login.min.css:13:33062
14:53:58.267 Unknown property ‘zoom’.  Declaration dropped.  login.min.css:13:33175
14:53:58.267 Unknown property ‘-moz-border-radius-topright’.  Declaration dropped.  login.min.css:13:33442
14:53:58.267 Unknown property ‘-moz-border-radius-bottomright’.  Declaration dropped.  login.min.css:13:33475
14:53:58.267 Unknown property ‘-moz-border-radius-topleft’.  Declaration dropped.  login.min.css:13:33681
14:53:58.267 Unknown property ‘-moz-border-radius-bottomleft’.  Declaration dropped.  login.min.css:13:33713
14:53:58.267 Unknown property ‘zoom’.  Declaration dropped.  login.min.css:13:34927
14:53:58.267 Unknown property ‘zoom’.  Declaration dropped.  login.min.css:13:35772
14:53:58.267 Unknown property ‘-moz-border-radius’.  Declaration dropped.  login.min.css:13:40030
14:53:58.267 Expected media feature name but found ‘-moz-min-device-pixel-ratio’.  login.min.css:13:41987
14:53:58.267 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  login.min.css:13:42037
14:53:58.267 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  login.min.css:13:42085
14:53:58.267 Expected media feature name but found ‘min-devicepixel-ratio’.  login.min.css:13:42138
14:53:58.267 Unknown property ‘-moz-box-shadow’.  Declaration dropped.  login.min.css:13:42773
14:53:58.268 Unknown property ‘-moz-border-radius’.  Declaration dropped.  login.min.css:13:44229
14:53:58.268 Unknown property ‘-moz-border-radius’.  Declaration dropped.  login.min.css:13:44357
14:53:58.268 Expected media feature name but found ‘-moz-min-device-pixel-ratio’.  login.min.css:13:44837
14:53:58.268 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  login.min.css:13:44887
14:53:58.268 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  login.min.css:13:44935
14:53:58.268 Expected media feature name but found ‘min-devicepixel-ratio’.  login.min.css:13:44988
14:53:58.268 Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  login.min.css:13:47278
14:53:58.268 Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  login.min.css:13:48086
14:53:58.268 Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.  login.min.css:13:52254
14:53:58.268 Expected media feature name but found ‘-moz-min-device-pixel-ratio’.  login.min.css:13:55416
14:53:58.268 Expected media feature name but found ‘-o-min-device-pixel-ratio’.  login.min.css:13:55466
14:53:58.268 Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.  login.min.css:13:55514
14:53:58.268 Expected media feature name but found ‘min-devicepixel-ratio’.  login.min.css:13:55567
14:53:58.277 Unknown property ‘font-weigth’.  Declaration dropped.  devel.min.css:10:1164
14:53:58.965 reflow: 0.7ms function <anonymous>, modernizr-custom.min.js line 4
14:53:58.966 reflow: 1ms function <anonymous>, modernizr-custom.min.js line 4
14:53:58.966 reflow: 0.19ms
14:53:58.967 reflow: 0.37ms
14:53:58.361 Unknown pseudo-class or pseudo-element ‘-webkit-scrollbar’.  Ruleset ignored due to bad selector.  login:1:54
14:53:58.361 Unknown pseudo-class or pseudo-element ‘-moz-scrollbar’.  Ruleset ignored due to bad selector.  login:1:95
14:53:58.362 Unknown pseudo-class or pseudo-element ‘-o-scrollbar’.  Ruleset ignored due to bad selector.  login:1:133
14:53:58.362 Unknown pseudo-class or pseudo-element ‘-ms-scrollbar’.  Ruleset ignored due to bad selector.  login:1:169
14:53:58.362 Unknown pseudo-class or pseudo-element ‘scrollbar’.  Ruleset ignored due to bad selector.  login:1:206
14:53:59.049 reflow: 4.55ms
14:53:59.050 reflow: 0.27ms function ue.support</<, onloadwff.js line 64
14:53:59.051 reflow: 0.14ms function ue.support</<, onloadwff.js line 64
14:53:59.051 reflow: 0.12ms function ue.support</</<, onloadwff.js line 64
14:53:59.052 reflow: 0.13ms function ue.support</<, onloadwff.js line 64
14:53:59.052 reflow: 0.16ms
14:53:59.067 GET XHR 
https://passbolt.localdomain.com/js/dist/bundles/app/login.js [HTTP/1.1 200 OK 0ms]
14:53:59.582 reflow: 0.53ms
14:54:00.171 Selector expected.  Ruleset ignored due to bad selector.  blank:10:5
14:54:00.171 Unexpected end of file while searching for closing } of invalid rule set.
```

**Comment by stripthis** [comment]
Seems same than #141 . We'll investigate.

**Comment by stripthis** [comment]
@tmidi are you also using centos like #141 ?

**Comment by cedricalfonsi** [comment]
@tmidi are you still encountering this issue with Firefox ?
What 's the version of the plugin ?

**Comment by rotanid** [comment]
it seems i am hitting the same bug. everything looks good, i enter the passphrase and after a bit of reloading the login page appears again.

**Comment by cedricalfonsi** [comment]
@rotanid Do you encounter this issue only on FF ? 
I'm not sure your issue is related to this one regarding the other comment you made on #163.

**Comment by rotanid** [comment]
@cedricalfonsi just tested again, it works fine in Chromium

**Comment by cedricalfonsi** [comment]
What's the version of your passbolt plugin?

**Comment by rotanid** [comment]
1.6.0

**Comment by cedricalfonsi** [comment]
@rotanid 

A new version is still pending approval from volunteers at Mozilla reviewing addons, but you can install it from the beta channel, it could solve your issue.

https://addons.mozilla.org/en-US/firefox/addon/passbolt/?src=userprofile#beta-channel

**Comment by tmidi** [comment]
@cedricalfonsi last time I checked (about 5 days ago) were still facing
this issue, unfortunately I can't provide me he current version using, but
will do once I'm back from vacation.
Thanks


On Aug 31, 2017 9:51 PM, "cedricalfonsi" <notifications@github.com> wrote:

@tmidi <https://github.com/tmidi> are you still encountering this issue
with Firefox ?
What 's the version of the plugin ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/passbolt/passbolt_api/issues/143#issuecomment-326417328>,
or mute the thread

**Comment by rotanid** [comment]
@cedricalfonsi just tested with 1.6.4-rc1 and the issue remains :-(

**Comment by rotanid** [comment]
@cedricalfonsi just tested with 1.6.4-rc1 and the issue remains :-(

but i found out the issue: i have "Accept third-party cookies" set to "Never"
changing that makes passbolt work, but that setting does also apply to every website you visit, so i won't change this.

**Comment by stripthis** [comment]
Closing due to inactivity. Please reopen a new issue if you encounter a similar problem as new healthcheck features may prevent this from happening.
