### ISSUE TITLE
An Internal Error has occured

### ISSUE THREAD

**Issue by ermisus** [passbolt/passbolt_api#225]
Hello,

I am getting HTTP 500 error and I found the details on nginx logs.

My Passbolt version is 1.6.9 nginx is 1.12 and PHP-FPM is 5.6 and/or 7.0. PHP version is does not change the final.

Here is the CakePHP logs; 
```
2018-02-14 15:34:05 Error: Fatal Error (1): Class 'gnupg' not found in [/var/www/passbolt/app/Controller/Component/Auth/GpgAuthenticate.php, line 176]
2018-02-14 15:34:05 Error: [InternalErrorException] Internal Server Error
Request URL: /index.php/auth/login
Stack Trace:
#0 /var/www/passbolt/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Class 'gnupg' n...', '/var/www/passbo...', 176)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'gnupg' n...', '/var/www/passbo...', 176, Array)
#2 /var/www/passbolt/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Class 'gnupg' n...', '/var/www/passbo...', 176, Array)
#3 /var/www/passbolt/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
```

Here is the nginx logs:
`[14/Feb/2018:15:34:05 +0300] "GET /index.php/auth/login HTTP/1.1" 500 2454 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"`

Passbolt trying to run on CentOS with disabled SELinux and fresh installed but no way. What is your idea?

**Comment by cedricalfonsi** [comment]
Hello @ermisus,

Could be the php gnup extension that is not installed. 

Did you run the healthcheck to get more information about your passbolt instance ? 
`~$ su -c "/var/www/passbolt/app/Console/cake passbolt healthcheck" -s /bin/bash nginx`
(from [centos passbolt install howto](https://medium.com/passbolt/passbolt-on-centos-7-with-nginx-php7-fpm-mariadb-from-scratch-7b2a9b15f3a4))

I don't know if you checked already the [community forum](https://community.passbolt.com/c/installation-issues), but there is a section "Installation issues" that could help you.

Thanks for your interest in passbolt.
Cheers

**Comment by ermisus** [comment]
Hello @cedricalfonsi,

Actually I installed gnupg via pecl. Here is the results:
```
Build process completed successfully
Installing '/usr/lib64/php/modules/gnupg.so'
install ok: channel://pecl.php.net/gnupg-1.4.0
configuration option "php_ini" is not set to php.ini location
You should add "extension=gnupg.so" to php.ini
[root@passbolt logs]# echo "extension=gnupg.so" > /etc/php.d/gnupg.ini
```

There is nothing wrong after healthcheck. Here is the healthcheck results;
```
---------------------------------------------------------------
     ____                  __          ____  
    / __ \____  _____ ____/ /_  ____  / / /_ 
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/ 
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /    
 /_/    \__,_/____/____/_.___/\____/_/\__/   

 Open source password manager for teams
---------------------------------------------------------------
 Healthcheck shell        
---------------------------------------------------------------

 Environment

 [PASS] PHP version 7.0.27
 [PASS] PCRE compiled with unicode support
 [PASS] The temporary directory and its content are writable
 [PASS] The public image directory and its content are writable

 Config files

 [PASS] The core config file is present
 [PASS] The database config file is present
 [PASS] The email config file is present
 [PASS] The application config file is present

 Core config

 [PASS] Debug mode is off.
 [PASS] Cache is working.
 [PASS] Unique value set for security.salt
 [PASS] Unique value set for security.cipherSeed
 [PASS] Full base url is set to https://passbolt.domain.tld
 [PASS] App.fullBaseUrl validation OK.
 [PASS] /healthcheck/status is reachable.

 SSL Certificate

 [PASS] SSL peer certificate validates
 [PASS] Hostname is matching in SSL certificate.
 [PASS] Not using a self-signed certificate

 Database

 [PASS] Configured to use a supported database backend
 [PASS] The application is able to connect to the database
 [PASS] Not using a prefix for database tables
 [FAIL] No table found
  [HELP] Run the install script to install the database tables
  [HELP] sudo su -s /bin/bash -c "/var/www/passbolt/app/Console/cake install" nginx
 [FAIL] No default content found
  [HELP] Run the install script to set the default content such as roles and permission types
  [HELP] sudo su -s /bin/bash -c "/var/www/passbolt/app/Console/cake install" nginx
 [PASS] The database schema up to date.

 GPG Configuration

 [PASS] PHP GPG Module is installed and loaded
 [PASS] The server gpg key is not the default one
 [PASS] The environment variable GNUPGHOME is set to /var/lib/nginx/.gnupg
 [PASS] The directory /var/lib/nginx/.gnupg containing the keyring is writable by the user the webserver is running as.
 [PASS] The public key file is defined in app/config.php and readable.
 [PASS] The private key file is defined in app/config.php and readable.
 [PASS] The server key fingerprint matches the one defined in app/config.php.
 [PASS] The server key defined in the app/Config.php is in the keyring.
 [PASS] There is a valid email id defined for the server key.
 [PASS] The public key can be used to encrypt and sign a message.
 [PASS] The private key can be used to decrypt a message.

 Application configuration

 [FAIL] This installation is not up to date. Currently using 1.6.9 and it should be v2.0.0-rc1.
  [HELP] See. https://www.passbolt.com/help/tech/update
 [PASS] Passbolt is configured to force SSL use
 [PASS] App.fullBaseUrl is set to HTTPS
 [PASS] Selenium API endpoints are disabled.
 [PASS] Search engine robots are told not to index content.
 [PASS] Registration is closed, only administrators can add users.
 [PASS] Serving the compiled version of the javascript app
 [PASS] All email notifications will be sent.

 Development Tools (optional)

 [PASS] Phpunit is installed
 [PASS] Phpunit version is 3.7.38

  3 error(s) found. Hang in there!
```

**Comment by cedricalfonsi** [comment]
Glad that it worked for you, you can show your support to the project by adding your star if it's not done yet :)
