### ISSUE TITLE
Error: [MissingTableException] Table authentication_tokens for model AuthenticationToken was not found in datasource default

### ISSUE THREAD

**Issue by ermisus** [passbolt/passbolt_api#226]
Hello everybody,

Passbolt v1.6.9, nginx, php70w-fpm and CentOS7 with SELinux disabled. After fresh install everything looks like fine but getting error at the first user creation.

**You can find app/tmp/logs/error.log below:**
```
2018-02-14 13:35:19 Error: [MissingTableException] Table authentication_tokens for model AuthenticationToken was not found in datasource default.
Exception Attributes: array (
  'table' => 'authentication_tokens',
  'class' => 'AuthenticationToken',
  'ds' => 'default',
)
Request URL: /index.php/setup/install/4d54fb53-ea61-3197-a12c-904e07cd01df/5cad9eaf-0a2a-4406-a261-8baca4210150
Stack Trace:
#0 /var/www/passbolt/lib/Cake/Model/Model.php(3667): Model->setSource('authentication_...')
#1 /var/www/passbolt/lib/Cake/Model/Model.php(834): Model->getDataSource()
#2 /var/www/passbolt/app/Controller/SetupController.php(59): Model->__call('findFirstByToke...', Array)
#3 [internal function]: SetupController->install('4d54fb53-ea61-3...', '5cad9eaf-0a2a-4...')
#4 /var/www/passbolt/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(SetupController), Array)
#5 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#6 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(SetupController), Object(CakeRequest))
#7 /var/www/passbolt/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#8 /var/www/passbolt/index.php(41): require('/var/www/passbo...')
#9 {main}
```

**Here is the MariaDB console output:**
```
MariaDB [(none)]> select passbolt;
ERROR 1054 (42S22): Unknown column 'passbolt' in 'field list'
MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| passbolt           |
+--------------------+
2 rows in set (0.01 sec)

MariaDB [(none)]> use passbolt;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [passbolt]> show tables;
+-----------------------------+
| Tables_in_passbolt          |
+-----------------------------+
| authentication_tokens       |
| cake_sessions               |
| comments                    |
| controller_logs             |
| email_queue                 |
| favorites                   |
| file_storage                |
| gpgkeys                     |
| groups                      |
| groups_users                |
| permissions                 |
| permissions_types           |
| profiles                    |
| resources                   |
| roles                       |
| schema_migrations           |
| secrets                     |
| user_agents                 |
| users                       |
| users_resources_permissions |
+-----------------------------+
20 rows in set (0.00 sec)

MariaDB [passbolt]> select * from authentication_tokens;
+--------------------------------------+--------------------------------------+--------------------------------------+--------+---------------------+---------------------+--------------------------------------+--------------------------------------+
| id                                   | token                                | user_id                              | active | created             | modified            | created_by                           | modified_by                          |
+--------------------------------------+--------------------------------------+--------------------------------------+--------+---------------------+---------------------+--------------------------------------+--------------------------------------+
| 5a843805-0f6c-446a-b2fb-0337b212cb39 | 5cad9eaf-0a2a-4406-a261-8baca4210150 | 4d54fb53-ea61-3197-a12c-904e07cd01df |      1 | 2018-02-14 13:22:13 | 2018-02-14 13:22:13 | c3b37726-7483-37fd-a185-a3f6b9ed0df1 | c3b37726-7483-37fd-a185-a3f6b9ed0df1 |
+--------------------------------------+--------------------------------------+--------------------------------------+--------+---------------------+---------------------+--------------------------------------+--------------------------------------+
1 row in set (0.00 sec)
```

Did you see before or did you know how can I fix it?

**Comment by stripthis** [comment]
Hi @ermisus can you open an issue on passbolt forum:
https://community.passbolt.com/c/installation-issues

We only use github issues for bugs and this seems like an installation issue.
Thanks,
