### ISSUE TITLE
Cant finalize creation of admin account : The key provided couldn't be used

### ISSUE THREAD

**Issue by gfriloux** [passbolt/passbolt_api#31]
Hello, when at last step of admin account creation (5. Login!), it fails : 
`Error! Something unexpected happened. The setup cannot be completed.`

Returned JSON :  
```json
{
  "error": "server response error",
  "setup": {
    "stepId": "login_redirection",
    "stepsHistory": "domain_check/define_key/secret/backup_key/security_token",
    "user": {
      "username": "guillaume@friloux.me",
      "firstname": "Guillaume",
      "lastname": "Friloux",
      "id": "_STRIPPED_"
    },
    "key": {
      "ownerName": "Guillaume Friloux",
      "ownerEmail": "guillaume@friloux.me",
      "comment": "",
      "length": "2048",
      "algorithm": "RSA-DSA",
      "passphrase": "",
      "publicKeyArmored": "-----BEGIN PGP PUBLIC KEY BLOCK-----\r\nVersion: OpenPGP.js v2.3.2\r\nComment: http://openpgpjs.org\r\n\r\nxsBNBFhxH/4BCADBZqzELEYL7N4h1M56FTgWRNUqiSTWymfBwhM78/TA4bWk\nK6SkeSI/cDfUH0WwkwlxGR318KliGklyQ6qAAqt6YLRjvXcbAO+Ma7YC3Xd1\n3MQPdgiDOM2LFCPT00QmNdnbmLANp5dMai30OBEEPU4xqWgqNf66RGjFOV7E\nBTjPZH8ihlqCoQyOXlnf84Us+EpFqKBD9AhWx9a64md50DjEvFu0hIIGM5OH\nbCZ6HISt7PDDmszbE0cvVvlyZLOsTAmEaI/oNl3v7IS/rUmwkgADR+tGaZNt\nAInVXtwcGlMl0UHOl5bF4Jz9z9x6M2NKCNz4mo86l57IQT/Y8bxlhHL3ABEB\nAAHNKEd1aWxsYXVtZSBGcmlsb3V4IDxndWlsbGF1bWVAZnJpbG91eC5tZT7C\nwHUEEAEIACkFAlhxH/8GCwkHCAMCCRC3/OgigYw5CwQVCAIKAxYCAQIZAQIb\nAwIeAQAAKdgH/12SDYvufRBJJDdps7d3xXE0z3vpiUXPNoe8XOUjLuiX8t9v\nW4QRxxszp31mBPFRgNKy1gEGyBMYkSikMCbH2fmz8B3c18kYIHg2W0L6OC7I\nSxOql7D5rDJutmBf9eSHYYv3YdeZNDXcab2zhv9eyBTz/wY4uGBcBOdXNbtL\ngGy5lJbS3PgW2RM+KWbOdnaqN1s9FNpw7Csz3nSwvvLO6CUyCCHV08HzFIr8\nSIM03eohhgPdHYS9TjBCYj3Tv3khfxrcKkQlW9rOytuR8grHKV4PhIcoQaXQ\no4wH5V6iomckPO0NoalwIJNY+/vrAN4tHutHxZA80WJCW8fTwsBCXafOwE0E\nWHEf/gEIAMs6OBH9bBfDAZmKyX5z6WSw1El6rqmWJR9gTjRazpEu7b/TNkUd\nZX08qjTh00eGqfM4g9I6eTJEULdyNF/5o+NU8ymSLcs5TVkMPeMa3BwBJ5dO\nLQu1V3OAXi71EHRPG7PlZxmXOHlg1ROrXtKF1c6SIuFaBUOnYHzOJFDignLG\n5j/Ee45VJC6nQDSjG6s3he9GVbSTPKRsolPq4ukVpCCUiyqyYFmHBRlMjc+F\nRbbW1EyYPOKLCQP/jgMSQNcKqtAzt9lfjjZsXF2qoNqDuGplOMu5dO9YyVlM\nRjPPpylC0etMcdpr6bcMu66V5rVO5IlTJwjSegphoqspWV4QKl8AEQEAAcLA\nXwQYAQgAEwUCWHEf/wkQt/zoIoGMOQsCGwwAAA2jCACozu0NrlC/ur7KC23T\nBc+jG8f7hftpCMp5c6vr3HjbO4c/31ENpZpvxwTve0Av3jeHRGs61rdpRUxV\nMyrHxuegjkawTKMzHmh9IA9lPNCilET3NMQ1udln2i0pqDucJocedQlr8FTN\ng4df7wKTs/w8IwtfCi7BNOahpsChqrRYVbmElZd6rPe8zsrHkz21ke6ZId6H\nDQ1us4F8D17twxUziW8wchFPK+rnk8sSLXRTMpg7p1nEeuZuIQrZnnTW+0QI\nv4MjPxLIl6B3SmNE+zcjIyjiE0AbbQBtSprOK8LxDTMPEL8fKQj5H9KVECzE\nMmDQ3hcvUNvSUDC7d4RZH6dj\r\n=FEr1\r\n-----END PGP PUBLIC KEY BLOCK-----\r\n\r\n",
      "privateKeyArmored": ""
    },
    "settings": {
      "token": "_STRIPPED_",
      "domain": "_STRIPPED_",
      "armoredServerKey": "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmQENBFhxCpIBCACteVEK3LRCcuS43B9oYZJbnFdv0ZjVKZRavge7St+v4906K07C\nHlrgyP85iXDLoJkzLp3EUrKol2FDoaoEflYS8MUyQbekd+5eVOUMAywHECMciqRV\nvI3h3OkB4MeGqt1zsTJ4GoPhElbXHQEAOsB4sU37Ce3spogaiPW4h6Hf8KQ9nASj\nfT7/nIvHpzzwMAw9t5wZFmn4F32chQnevCxyyNuwPrGJ+bM8Amq5M3PSn6tu4eRw\nqq2pCyrfjAZUiMI2gTsVtgRDfP6BytxP6whoGhhwRGaVD4YryoLZSLFglL1+94PU\ngi8bNiOE44YPvmTzi5ZhH1W49R7gSj9wWdyFABEBAAG0IXBhc3MuZnJpbG91eC5t\nZSA8cm9vdEBmcmlsb3V4Lm1lPokBVAQTAQgAPhYhBAVLawnTMgZKU5wdALix+NJr\ndHisBQJYcQqSAhsDBQkDwmcABQsJCAcCBhUICQoLAgQWAgMBAh4BAheAAAoJELix\n+NJrdHisKm0H/jU4fW1t0bgD000SONerBbLJeQVm35JGRhywzXBAQvhSbudi2uLw\n4tc3Lr844/3/uxFJqFrcG3OhCKl/bm6kaMu3fXLymLZ3qNkfTbFtqHrmwKShGTM3\n6tJ6a0Y/A0YRKuL65BrSWPyAVooy9s7ZtUmdw7D6ie5HJ9cAmyw96dlZbaZIDCEZ\nlCNtb0TU8DurtNWM3g0XzuvxsXq2Kqbx7EuQ/et+qrI28t99HB275bXbHG3TSCB7\ndkErzJWzNzNHPMhlR3LAu5YAnRAMaMwoayTEOpr4L1SugRwsUPEzHTz70QrSAPm5\nQ+NyZuGUqPAfpXE47YdiR8j0kVb/YJGbUoC5AQ0EWHEKkgEIALsBLZxs9XlXCh9w\nEWwPRwZ6AdDHBGqOThrSk6X8dSlwWRy23lE83rYUU64R5sNEKIM0HxNox/N4z+oC\nyw0E0YHAhcVfDiX6N4GVxTpC3f4fNeZ2lpHjyTerjuvI9/Vv4cVJiLOz0eYw7tqY\nFwgQHC0dnV8BzSJQm6QcQqoBKTae6CiyH7vHsTxNwuuNaFZvLdWLssU/aaDn0aHa\npJwxi8MKyvAlWkq5x56xIMX8sP5pj++uUt9Fk7of6mTTiYGKG6UVp99jfCmOkUdW\nL19nPZtyRzMG87DJAYDS8rnCW8DBsphxnTvSk1Y0IgZC8zIQ+pNLe7TJdfnMaB7j\nW9q2h/kAEQEAAYkBPAQYAQgAJhYhBAVLawnTMgZKU5wdALix+NJrdHisBQJYcQqS\nAhsMBQkDwmcAAAoJELix+NJrdHis878IAKeWjHMekkCo+PWxKf+WILagiewv8DtC\njpH0+r9/BX3Q+8PUVC3Vg1rusAeNNDyg7UB2yWvaArfHTC3udwWBGpXcmkTCPJmy\nM/nx13aB/uqm/SjEQqZ/T78iXfI0aYNLK6TCC4HcnU23Ddof4e9y0yP9Upxc1r4h\nV8psED+mV/SwF0XCgF+a0eOgD88f6yriyx+e8h9LZ3SBDA1mUn7O3fYwyFDXmwAb\ntqYSuMNWSVNuQUhJpwQsL/QDuuReTddWJ3XrHPDKukZI016bd9rMqFLBTlZV9RNU\nJfV/qb1CR1MNC8x5vnK1t2kDUHAyITE4dxsLq1udHE7dS6zUeN+JkOo=\n=OPdW\n-----END PGP PUBLIC KEY BLOCK-----\n",
      "securityToken": {
        "code": "_STRIPPED_",
        "color": "_STRIPPED_",
        "textcolor": "#000"
      }
    }
  },
  "additional": {
    "request": {
      "AuthenticationToken": {
        "token": "_STRIPPED_"
      },
      "Gpgkey": {
        "key": "-----BEGIN PGP PUBLIC KEY BLOCK-----\r\nVersion: OpenPGP.js v2.3.2\r\nComment: http://openpgpjs.org\r\n\r\nxsBNBFhxH/4BCADBZqzELEYL7N4h1M56FTgWRNUqiSTWymfBwhM78/TA4bWk\nK6SkeSI/cDfUH0WwkwlxGR318KliGklyQ6qAAqt6YLRjvXcbAO+Ma7YC3Xd1\n3MQPdgiDOM2LFCPT00QmNdnbmLANp5dMai30OBEEPU4xqWgqNf66RGjFOV7E\nBTjPZH8ihlqCoQyOXlnf84Us+EpFqKBD9AhWx9a64md50DjEvFu0hIIGM5OH\nbCZ6HISt7PDDmszbE0cvVvlyZLOsTAmEaI/oNl3v7IS/rUmwkgADR+tGaZNt\nAInVXtwcGlMl0UHOl5bF4Jz9z9x6M2NKCNz4mo86l57IQT/Y8bxlhHL3ABEB\nAAHNKEd1aWxsYXVtZSBGcmlsb3V4IDxndWlsbGF1bWVAZnJpbG91eC5tZT7C\nwHUEEAEIACkFAlhxH/8GCwkHCAMCCRC3/OgigYw5CwQVCAIKAxYCAQIZAQIb\nAwIeAQAAKdgH/12SDYvufRBJJDdps7d3xXE0z3vpiUXPNoe8XOUjLuiX8t9v\nW4QRxxszp31mBPFRgNKy1gEGyBMYkSikMCbH2fmz8B3c18kYIHg2W0L6OC7I\nSxOql7D5rDJutmBf9eSHYYv3YdeZNDXcab2zhv9eyBTz/wY4uGBcBOdXNbtL\ngGy5lJbS3PgW2RM+KWbOdnaqN1s9FNpw7Csz3nSwvvLO6CUyCCHV08HzFIr8\nSIM03eohhgPdHYS9TjBCYj3Tv3khfxrcKkQlW9rOytuR8grHKV4PhIcoQaXQ\no4wH5V6iomckPO0NoalwIJNY+/vrAN4tHutHxZA80WJCW8fTwsBCXafOwE0E\nWHEf/gEIAMs6OBH9bBfDAZmKyX5z6WSw1El6rqmWJR9gTjRazpEu7b/TNkUd\nZX08qjTh00eGqfM4g9I6eTJEULdyNF/5o+NU8ymSLcs5TVkMPeMa3BwBJ5dO\nLQu1V3OAXi71EHRPG7PlZxmXOHlg1ROrXtKF1c6SIuFaBUOnYHzOJFDignLG\n5j/Ee45VJC6nQDSjG6s3he9GVbSTPKRsolPq4ukVpCCUiyqyYFmHBRlMjc+F\nRbbW1EyYPOKLCQP/jgMSQNcKqtAzt9lfjjZsXF2qoNqDuGplOMu5dO9YyVlM\nRjPPpylC0etMcdpr6bcMu66V5rVO5IlTJwjSegphoqspWV4QKl8AEQEAAcLA\nXwQYAQgAEwUCWHEf/wkQt/zoIoGMOQsCGwwAAA2jCACozu0NrlC/ur7KC23T\nBc+jG8f7hftpCMp5c6vr3HjbO4c/31ENpZpvxwTve0Av3jeHRGs61rdpRUxV\nMyrHxuegjkawTKMzHmh9IA9lPNCilET3NMQ1udln2i0pqDucJocedQlr8FTN\ng4df7wKTs/w8IwtfCi7BNOahpsChqrRYVbmElZd6rPe8zsrHkz21ke6ZId6H\nDQ1us4F8D17twxUziW8wchFPK+rnk8sSLXRTMpg7p1nEeuZuIQrZnnTW+0QI\nv4MjPxLIl6B3SmNE+zcjIyjiE0AbbQBtSprOK8LxDTMPEL8fKQj5H9KVECzE\nMmDQ3hcvUNvSUDC7d4RZH6dj\r\n=FEr1\r\n-----END PGP PUBLIC KEY BLOCK-----\r\n\r\n"
      }
    },
    "response": {
      "header": {
        "id": "_STRIPPED_",
        "status": "error",
        "title": "app_users_validateaccount_error",
        "servertime": 1483808592,
        "message": "The key provided couldn't be used",
        "controller": "Users",
        "action": "validateAccount"
      },
      "body": []
    }
  }
}
```

I dont doubt i made something wrong, but i have no idea what.
Tell me anything you need to figure out the issue.

**Comment by kevinmuller** [comment]
Hi Guillaume,

Is this happening on a self hosted instance, or on the online demo ? In case of a self hosted instance (as it seems), could you try the same on the [online demo](https://demo.passbolt.com) and see if it works ?

Can you also check:
- is there anything in your Apache / PHP logs ?
- is there anything in the passbolt logs ? (app/tmp/logs/error.log or app/tmp/logs/debug.log) 

And also could you tell me what's the version of PHP you are using ?

I'd be inclined to think that it's a PHP issue. Since the key pair was generated by openpgpjs, it's probably not a key format issue.

Thanks.
Kevin

**Comment by gfriloux** [comment]
1. It happens on self hosted instance.
2. I dont have any error log being written by nginx when this happens.
3. Thank you for pointing me to location of errors logs for passbolt! they indeed contain interesting data!


Full error.log : https://transfer.sh/zpHra/error.log.

Last two entries : 
```
2017-01-08 18:13:38 Warning: Warning (512): SplFileInfo::openFile(/usr/share/webapps/passbolt/app/tmp/cache/models/passbolt_cake_model_default_pass_roles) [<a href='http://php.net/splfileinfo.openfile'>splfileinfo.openfile</a>]: failed to open stream: Permission denied in [/usr/share/webapps/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
FileEngine::_setKey() - CORE/Cake/Cache/Engine/FileEngine.php, line 356
FileEngine::write() - CORE/Cake/Cache/Engine/FileEngine.php, line 116
Cache::write() - CORE/Cake/Cache/Cache.php, line 317
DataSource::_cacheDescription() - CORE/Cake/Model/Datasource/DataSource.php, line 310
Mysql::describe() - CORE/Cake/Model/Datasource/Database/Mysql.php, line 373
Model::schema() - CORE/Cake/Model/Model.php, line 1397
Model::getColumnType() - CORE/Cake/Model/Model.php, line 1438
Model::getColumnType() - CORE/Cake/Model/Model.php, line 1455
DboSource::_parseKey() - CORE/Cake/Model/Datasource/DboSource.php, line 2882
DboSource::conditionKeysToString() - CORE/Cake/Model/Datasource/DboSource.php, line 2833
DboSource::conditions() - CORE/Cake/Model/Datasource/DboSource.php, line 2714
DboSource::buildStatement() - CORE/Cake/Model/Datasource/DboSource.php, line 2007
DboSource::buildAssociationQuery() - CORE/Cake/Model/Datasource/DboSource.php, line 1735
DboSource::read() - CORE/Cake/Model/Datasource/DboSource.php, line 1182
Model::_readDataSource() - CORE/Cake/Model/Model.php, line 3038
Model::find() - CORE/Cake/Model/Model.php, line 3010
User::setActive() - APP/Model/User.php, line 401
User::get() - APP/Model/User.php, line 359
ControllerLog::write() - APP/Model/ControllerLog.php, line 176
MessageComponent::__add() - APP/Controller/Component/MessageComponent.php, line 242
MessageComponent::success() - APP/Controller/Component/MessageComponent.php, line 187
AuthController::verify() - APP/Controller/AuthController.php, line 82
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 110

2017-01-08 18:13:38 Warning: Warning (512): _cake_model_ cache was unable to write 'default_pass_roles' to File cache in [/usr/share/webapps/passbolt/lib/Cake/Cache/Cache.php, line 327]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
Cache::write() - CORE/Cake/Cache/Cache.php, line 327
DataSource::_cacheDescription() - CORE/Cake/Model/Datasource/DataSource.php, line 310
Mysql::describe() - CORE/Cake/Model/Datasource/Database/Mysql.php, line 373
Model::schema() - CORE/Cake/Model/Model.php, line 1397
Model::getColumnType() - CORE/Cake/Model/Model.php, line 1438
Model::getColumnType() - CORE/Cake/Model/Model.php, line 1455
DboSource::_parseKey() - CORE/Cake/Model/Datasource/DboSource.php, line 2882
DboSource::conditionKeysToString() - CORE/Cake/Model/Datasource/DboSource.php, line 2833
DboSource::conditions() - CORE/Cake/Model/Datasource/DboSource.php, line 2714
DboSource::buildStatement() - CORE/Cake/Model/Datasource/DboSource.php, line 2007
DboSource::buildAssociationQuery() - CORE/Cake/Model/Datasource/DboSource.php, line 1735
DboSource::read() - CORE/Cake/Model/Datasource/DboSource.php, line 1182
Model::_readDataSource() - CORE/Cake/Model/Model.php, line 3038
Model::find() - CORE/Cake/Model/Model.php, line 3010
User::setActive() - APP/Model/User.php, line 401
User::get() - APP/Model/User.php, line 359
ControllerLog::write() - APP/Model/ControllerLog.php, line 176
MessageComponent::__add() - APP/Controller/Component/MessageComponent.php, line 242
MessageComponent::success() - APP/Controller/Component/MessageComponent.php, line 187
AuthController::verify() - APP/Controller/AuthController.php, line 82
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 110

2017-01-08 18:13:38 Warning: Warning (512): SplFileInfo::openFile(/usr/share/webapps/passbolt/app/tmp/cache/persistent/passbolt_cake_core_method_cache) [<a href='http://php.net/splfileinfo.openfile'>splfileinfo.openfile</a>]: failed to open stream: Permission denied in [/usr/share/webapps/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
FileEngine::_setKey() - CORE/Cake/Cache/Engine/FileEngine.php, line 356
FileEngine::write() - CORE/Cake/Cache/Engine/FileEngine.php, line 116
Cache::write() - CORE/Cake/Cache/Cache.php, line 317
DboSource::__destruct() - CORE/Cake/Model/Datasource/DboSource.php, line 3662
[main] - [internal], line ??

2017-01-08 18:13:38 Warning: Warning (512): _cake_core_ cache was unable to write 'method_cache' to File cache in [/usr/share/webapps/passbolt/lib/Cake/Cache/Cache.php, line 327]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
Cache::write() - CORE/Cake/Cache/Cache.php, line 327
DboSource::__destruct() - CORE/Cake/Model/Datasource/DboSource.php, line 3662
[main] - [internal], line ??
```

Indeed i have a few files owned by root!
I did "app/Console/cake install --no-admin" as root the first time, then i restarted it with http user, but bad things were already made.

So i just made
```
[root@friloux passbolt]# chown http:http * -R
```

But the problem this happens, and this time im getting what seems to be the real issue : 
```
2017-01-09 11:51:46 Error: [BadRequestException] The key provided couldn't be used
Request URL: /users/validateAccount/_STRIPED_.json
Stack Trace:
#0 /usr/share/webapps/passbolt/app/Controller/UsersController.php(586): MessageComponent->error('The key provide...')
#1 [internal function]: UsersController->validateAccount('58710f0f-4b38-4...')
#2 /usr/share/webapps/passbolt/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 /usr/share/webapps/passbolt/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 /usr/share/webapps/passbolt/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#5 /usr/share/webapps/passbolt/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
```

**Comment by kevinmuller** [comment]
Alright. The logs don't really help here. It shows that we could probably improve the error logging for this part.

What about the healthcheck page ? Is everything normal ?

If healthcheck is ok, then give me some time, I will send you some files to replace (Gpgkey.php / Gpg.php) with more logging / debugging statements, just for the sake of understanding what's going on.

**Comment by gfriloux** [comment]
I've read i need to enable debug mode for /healthcheck to work.
But i dont know how to enable it, which result in : 
```
Forbidden
Error: The requested address '/healthcheck' was not found on this server.
```

**Comment by kevinmuller** [comment]
To enable the debug mode, you can edit the file app/Config/core.php and modify this line "Configure::write('debug', 0);" into this "Configure::write('debug', 1);"

**Comment by gfriloux** [comment]
Ok so healthcheck tells me : 
```
PHP GPG Module is not installed / enabled.
```

yaourt tells me : 
```
aur/php-gnupg 1.4.0-2 [installed] (3) (0,00)
    PHP extension for gnupg/gpgme.
```

gnupg : 
```
[root@friloux passbolt]# cat /etc/php/conf.d/gnupg.ini 
extension=gnupg.so
```

So i did restart php-fpm, and now it says : 
```
PHP GPG Module is on.
```

So i clearly did wrong on this.
And now it works !

Would it be possible to enhance https://www.passbolt.com/help/tech/install to tell how to turn debug mode so healthcheck works ? This might help other users that are as prone as me to do things wrong.

Thanks for your help, you troubleshooted it fast, and i really appreciate it!

**Comment by gfriloux** [comment]
Damn, cant login, i have another issue.

**Comment by gfriloux** [comment]
Since i completed the creation of admin account, seems things got broken.

Getting / now returns a 403 error, with nginx saying : 
```
2017/01/09 13:14:06 [error] 13639#13639: *19 directory index of "/usr/share/webapps/passbolt/" is forbidden, client: 77.147.234.178, server: pass.friloux.me, request: "GET / HTTP/1.1", host: "pass.friloux.me"
```

And healthcheck says everything is good.

**Comment by gfriloux** [comment]
Ok, added
```
index index.php;
```

My noob skills are really high, sorry for making you read this :/

**Comment by kevinmuller** [comment]
Ha ha. No issues ! Glad that it's working fine finally :)
