### ISSUE TITLE
Error on Installation

### ISSUE THREAD

**Issue by yannik995** [passbolt/passbolt_api#58]
HI,

if I start the installation I get this Error:

```
sudo su -s /bin/bash -c "app/Console/cake install --no-admin" www-data
     ____                  __          ____
    / __ \____  _____ ____/ /_  ____  / / /_
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /
 /_/    \__,_/____/____/_.___/\____/_/\__/

 Open source password manager for teams
 (c) 2015-present passbolt.com

---------------------------------------------------------------
 Avatar deleted!
Installing schema / database
---------------------------------------------------------------

Welcome to CakePHP v2.9.4 Console
---------------------------------------------------------------
App : app
Path: /var/www/passbolt/app/
---------------------------------------------------------------
Cake Schema Shell
---------------------------------------------------------------
Error: Database connection "Mysql" is missing, or could not be created.
#0 /var/www/passbolt/lib/Cake/Model/Datasource/DboSource.php(269): Mysql->connect()
#1 /var/www/passbolt/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#2 /var/www/passbolt/app/Console/Command/SchemaShell.php(317): ConnectionManager::getDataSource('default')
#3 /var/www/passbolt/app/Console/Command/SchemaShell.php(251): SchemaShell->_create(Object(AppSchema), NULL)
#4 /var/www/passbolt/lib/Cake/Console/Shell.php(458): SchemaShell->create()
#5 /var/www/passbolt/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('create', Array)
#6 /var/www/passbolt/lib/Cake/Console/Shell.php(399): ShellDispatcher->dispatch()
#7 /var/www/passbolt/app/Console/Command/InstallShell.php(288): Shell->dispatchShell('schema create -...')
#8 /var/www/passbolt/app/Console/Command/InstallShell.php(124): InstallShell->schema()
#9 /var/www/passbolt/lib/Cake/Console/Shell.php(461): InstallShell->main()
#10 /var/www/passbolt/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('--no-admin', Array)
#11 /var/www/passbolt/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#12 /var/www/passbolt/app/Console/cake.php(47): ShellDispatcher::run(Array)
#13 {main}
```

A connect with mysql works.

php -v
PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )

mysqld -V
mysqld  Ver 10.1.21-MariaDB-1~xenial for debian-linux-gnu on x86_64

[PHP Modules]
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gnupg
hash
iconv
imagick
intl
json
libxml
mbstring
mcrypt
memcached
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

```
class DATABASE_CONFIG {

        public $default = array(
                'datasource' => 'Database/Mysql',
                'persistent' => false,
                'host' => 'localhost',
                'login' => 'passbolt',
                'password' => 'passbolt',
                'database' => 'passbolt',
                'prefix' => '',
                'encoding' => 'utf8',
        );

        public $test = array(
                'datasource' => 'Database/Mysql',
                'persistent' => false,
                'host' => 'localhost',
                'login' => 'user',
                'password' => 'password',
                'database' => 'test_database_name',
                'prefix' => '',
                'encoding' => 'utf8',
        );
}

```

**Comment by stripthis** [comment]
Hi @yannik995,

This could come from several reasons, like the mysql driver is not accessible by php in command line, or your database name or user name is mispelled, etc. Can you try to connect with a simple php script and see if this works?

http://php.net/manual/en/pdo.connections.php

**Comment by yannik995** [comment]
Okay, thanks.

It fails with localhost but suceed with 127.0.0.1

Changed Config/database.php and the installation works fine.
