### ISSUE TITLE
Error on installation "Database connection "Mysql" is missing, or could not be created".

### ISSUE THREAD

**Issue by kumaip** [passbolt/passbolt_api#80]
Hello, 
 su -s /bin/bash -c "app/Console/cake install --no-admin" www-data 
---------------------------------------------------------------
     ____                  __          ____  
    / __ \____  _____ ____/ /_  ____  / / /_ 
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/ 
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /    
 /_/    \__,_/____/____/_.___/\____/_/\__/   

 Open source password manager for teams
---------------------------------------------------------------
 Install shell
---------------------------------------------------------------
 Avatar deleted!
Installing schema / database
---------------------------------------------------------------
---------------------------------------------------------------
     ____                  __          ____  
    / __ \____  _____ ____/ /_  ____  / / /_ 
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/ 
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /    
 /_/    \__,_/____/____/_.___/\____/_/\__/   

 Open source password manager for teams
---------------------------------------------------------------
Cake Schema Shell
---------------------------------------------------------------
Error: Database connection "Mysql" is missing, or could not be created.
#0 /var/www/passbolt/lib/Cake/Model/ConnectionManager.php(105): DboSource->__construct(Array)
#1 /var/www/passbolt/app/Console/Command/SchemaShell.php(317): ConnectionManager::getDataSource('default')
#2 /var/www/passbolt/app/Console/Command/SchemaShell.php(251): SchemaShell->_create(Object(AppSchema), NULL)
#3 /var/www/passbolt/lib/Cake/Console/Shell.php(458): SchemaShell->create()
#4 /var/www/passbolt/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('create', Array)
#5 /var/www/passbolt/lib/Cake/Console/Shell.php(399): ShellDispatcher->dispatch()
#6 /var/www/passbolt/app/Console/Command/InstallShell.php(273): Shell->dispatchShell('schema create -...')
#7 /var/www/passbolt/app/Console/Command/InstallShell.php(109): InstallShell->schema()
#8 /var/www/passbolt/lib/Cake/Console/Shell.php(461): InstallShell->main()
#9 /var/www/passbolt/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('--no-admin', Array)
#10 /var/www/passbolt/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#11 /var/www/passbolt/app/Console/cake.php(47): ShellDispatcher::run(Array)
#12 {main}

PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21) 
Copyright (c) 1997-2016 The PHP Group

Debian jessie

I followed this topic, with the same conf : 
https://medium.com/passbolt/passbolt-on-debian-8-71-from-scratch-4438dad18908

**Comment by kumaip** [comment]
I just reinstalled php5_mysqlnd, and everything works fine now
