### ISSUE TITLE
Running email cron job as root fails to send emails

### ISSUE THREAD

**Issue by strideynet** [passbolt/passbolt_api#84]
Hi there,  
My Ubuntu 16.04 installation of Passbolt fails to send mail but nothing is logged in regards to this. Nothing was being logged by the cron job so I ran the cake console command directly and only got the following output:  
```
root@passbolt:/var/www/passbolt# ./app/Console/cake EmailQueue.sender
---------------------------------------------------------------
     ____                  __          ____
    / __ \____  _____ ____/ /_  ____  / / /_
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /
 /_/    \__,_/____/____/_.___/\____/_/\__/

 Open source password manager for teams
---------------------------------------------------------------
root@passbolt:/var/www/passbolt# ./app/Console/cake EmailQueue.sender -v
---------------------------------------------------------------
     ____                  __          ____
    / __ \____  _____ ____/ /_  ____  / / /_
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /
 /_/    \__,_/____/____/_.___/\____/_/\__/

 Open source password manager for teams
---------------------------------------------------------------
```  
By using the EmailQueue command as I was able to check that there was mail in the queue.
  
Where can I start to check?

**Comment by stripthis** [comment]
Ref. PASSBOLT-2104

**Comment by cedricalfonsi** [comment]
Hello @strideynet,

The email queue cron job should be launched as apache/nginx user.
Root shouldn't be used to start the job or it will corrupt tmp data.

Can you retry with your apache/nginx user ? and tell us how it goes.

**Comment by strideynet** [comment]
```
sudo -u www-data ./app/Console/cake EmailQueue.sender
---------------------------------------------------------------
     ____                  __          ____
    / __ \____  _____ ____/ /_  ____  / / /_
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /
 /_/    \__,_/____/____/_.___/\____/_/\__/

 Open source password manager for teams
---------------------------------------------------------------
```
Still no real output of data

**Comment by cedricalfonsi** [comment]
@strideynet,

Do you have something in your log file that could be relative to this ?
`./app/tmp/logs/error.log`

**Comment by strideynet** [comment]
```
2017-06-14 15:33:40 Error: [ForbiddenException] You need to login to access this location
Request URL: /auth/checkSession.json
Stack Trace:
#0 /var/www/passbolt/lib/Cake/Controller/Component/AuthComponent.php(349): GpgAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/passbolt/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(AuthController))
#2 [internal function]: AuthComponent->startup(Object(AuthController))
#3 /var/www/passbolt/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#4 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#5 /var/www/passbolt/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#6 /var/www/passbolt/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#7 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AuthController), Object(CakeRequest))
#9 /var/www/passbolt/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
```
Is the only thing repeating in the logs

**Comment by strideynet** [comment]
Hello?

**Comment by kevinmuller** [comment]
@strideynet 
Could it be that your email provider is using TLS  ? 
Can you try adding the following configuration line in your email.php config file, default section:
```
'tls' => true,
```

**Comment by kevinmuller** [comment]
Hi @strideynet 
Did you try the solution above ? Any update?

**Comment by strideynet** [comment]
I have tried this and have not been successful.

**Comment by stripthis** [comment]
@strideynet can you try the solution that worked for #119. Feel free to reopen the ticket if it didn't fix the issue.
